// import GameArgs from "./Game";
// import { GameArgs, NBAGame, NHLGame } from "./Game";

interface TeamData {
     abbreviation: string; name: string; colorDark: string; colorLight: string; colorThird: string,
};

//   export const getMatchWinner = (game: GameArgs<any>): string => {
//     if ('league' in game && (game.league.id === 12 || game.league.id === 13)) { // NBA league ID
//         const { scores } = game as NBAGame;
//         if (scores.home.total > scores.away.total) {
//             return game.teams.home.name;
//         } else if (scores.away.total > scores.home.total) {
//             return game.teams.away.name;
//         } else {
//             return "Draw";
//         }
//     } else if ('league' in game && game.league.id === 57) { // NHL league ID
//         const { scores } = game as NHLGame;
//         if (scores.home > scores.away) {
//             return game.teams.home.name;
//         } else if (scores.away > scores.home) {
//             return game.teams.away.name;
//         } else {
//             return "Draw";
//         }
//     } else {
//         return "Invalid match object";
//     }
// };

export const getTeamData = (teamName: string, text: boolean): TeamData => {
  // const tailwindClass = (color: string) => (text ? `text-[${color}]` : `bg-[${color}]`);

  
  const teamData = {
  
    // WNBA
    'Atlanta Dream W': { abbreviation: 'ATL', name: 'Atlanta Dream', colorDark: '#002a5c', colorLight: '#e8c6a0', colorThird: '#fdb927' },
    'Chicago Sky W': { abbreviation: 'CHI', name: 'Chicago Sky', colorDark: '#1d428a', colorLight: '#fdbb30', colorThird: '#8d9093' },
    'Connecticut Sun W': { abbreviation: 'CON', name: 'Connecticut Sun', colorDark: '#8d9093', colorLight: '#e56020', colorThird: '#fdb927' },
    'Dallas Wings W': { abbreviation: 'DAL', name: 'Dallas Wings', colorDark: '#1d428a', colorLight: '#00843d', colorThird: '#c8102e' },
    'Indiana Fever W': { abbreviation: 'IND', name: 'Indiana Fever', colorDark: '#041e42', colorLight: '#c8102e', colorThird: '#fdb927' },
    'Las Vegas Aces W': { abbreviation: 'LVA', name: 'Las Vegas Aces', colorDark: '#85714d', colorLight: '#c8102e', colorThird: '#1d1160' },
    'Los Angeles Sparks W': { abbreviation: 'LAS', name: 'Los Angeles Sparks', colorDark: '#552583', colorLight: '#fdb927', colorThird: '#dc4405' },
    'Minnesota Lynx W': { abbreviation: 'MIN', name: 'Minnesota Lynx', colorDark: '#002b5c', colorLight: '#78be20', colorThird: '#fdb927' },
    'New York Liberty W': { abbreviation: 'NYL', name: 'New York Liberty', colorDark: '#244289', colorLight: '#dc4405', colorThird: '#8d9093' },
    'Phoenix Mercury W': { abbreviation: 'PHX', name: 'Phoenix Mercury', colorDark: '#1d1160', colorLight: '#8a2583', colorThird: '#c8102e' },
    'Seattle Storm W': { abbreviation: 'SEA', name: 'Seattle Storm', colorDark: '#2c5234', colorLight: '#fdb927', colorThird: '#dc4405' },
    'Washington Mystics W': { abbreviation: 'WAS', name: 'Washington Mystics', colorDark: '#002b5c', colorLight: '#e31837', colorThird: '#c8102e' },
      // NBA
      'Atlanta Hawks': { abbreviation: 'ATL', name: 'Atlanta Hawks', colorDark: '#e03a3e', colorLight: '#c1d32f', colorThird: '#fdb927' },
      'Boston Celtics': { abbreviation: 'BOS', name: 'Boston Celtics', colorDark: '#008348', colorLight: '#ba9653', colorThird: '#fdb927' },
      'Brooklyn Nets': { abbreviation: 'BKN', name: 'Brooklyn Nets', colorDark: '#000000', colorLight: '#c4ced4', colorThird: '#ffffff' },
      'Charlotte Hornets': { abbreviation: 'CHA', name: 'Charlotte Hornets', colorDark: '#00788c', colorLight: '#a1a1a4', colorThird: '#fdb927' },
      'Chicago Bulls': { abbreviation: 'CHI', name: 'Chicago Bulls', colorDark: '#ce1141', colorLight: '#ce1141', colorThird: '#ffffff' },
      'Cleveland Cavaliers': { abbreviation: 'CLE', name: 'Cleveland Cavaliers', colorDark: '#6f263d', colorLight: '#FEC524', colorThird: '#fdb927' },
      'Dallas Mavericks': { abbreviation: 'DAL', name: 'Dallas Mavericks', colorDark: '#00538c', colorLight: '#00538C', colorThird: '#fdb927' },
      'Denver Nuggets': { abbreviation: 'DEN', name: 'Denver Nuggets', colorDark: '#0e2240', colorLight: '#ffc627', colorThird: '#fdb927' },
      'Detroit Pistons': { abbreviation: 'DET', name: 'Detroit Pistons', colorDark: '#c8102e', colorLight: '#c8102e', colorThird: '#ffffff' },
      'Golden State Warriors': { abbreviation: 'GSW', name: 'Golden State Warriors', colorDark: '#1d428a', colorLight: '#fdb927', colorThird: '#ffffff' },
      'Houston Rockets': { abbreviation: 'HOU', name: 'Houston Rockets', colorDark: '#ce1141', colorLight: '#ce1141', colorThird: '#ffffff' },
      'Indiana Pacers': { abbreviation: 'IND', name: 'Indiana Pacers', colorDark: '#002d62', colorLight: '#fdbb30', colorThird: '#fdb927' },
      'Los Angeles Clippers': { abbreviation: 'LAC', name: 'Los Angeles Clippers', colorDark: '#c8102e', colorLight: '#c8102e', colorThird: '#ffffff' },
      'Los Angeles Lakers': { abbreviation: 'LAL', name: 'Los Angeles Lakers', colorDark: '#552583', colorLight: '#fdb927', colorThird: '#ffffff' },
      'Memphis Grizzlies': { abbreviation: 'MEM', name: 'Memphis Grizzlies', colorDark: '#5d76a9', colorLight: '#ffbb22', colorThird: '#fdb927' },
      'Miami Heat': { abbreviation: 'MIA', name: 'Miami Heat', colorDark: '#98002e', colorLight: '#f9a01b', colorThird: '#ffffff' },
      'Milwaukee Bucks': { abbreviation: 'MIL', name: 'Milwaukee Bucks', colorDark: '#00471b', colorLight: '#eee1c6', colorThird: '#fdb927' },
      'Minnesota Timberwolves': { abbreviation: 'MIN', name: 'Minnesota Timberwolves', colorDark: '#236192', colorLight: '#236192', colorThird: '#fdb927' },
      'New Orleans Pelicans': { abbreviation: 'NOP', name: 'New Orleans Pelicans', colorDark: '#0c2340', colorLight: '#b4975a', colorThird: '#fdb927' },
      'New York Knicks': { abbreviation: 'NYK', name: 'New York Knicks', colorDark: '#006bb6', colorLight: '#f58426', colorThird: '#ffffff' },
      'Oklahoma City Thunder': { abbreviation: 'OKC', name: 'Oklahoma City Thunder', colorDark: '#007ac1', colorLight: '#fdbb30', colorThird: '#ffffff' },
      'Orlando Magic': { abbreviation: 'ORL', name: 'Orlando Magic', colorDark: '#0077c0', colorLight: '#c4ced4', colorThird: '#fdb927' },
      'Philadelphia 76ers': { abbreviation: 'PHI', name: 'Philadelphia 76ers', colorDark: '#006bb6', colorLight: '#ed174c', colorThird: '#fdb927' },
      'Phoenix Suns': { abbreviation: 'PHX', name: 'Phoenix Suns', colorDark: '#1d1160', colorLight: '#e56020', colorThird: '#fdb927' },
      'Portland Trail Blazers': { abbreviation: 'POR', name: 'Portland Trail Blazers', colorDark: '#e03a3e', colorLight: '#e03a3e', colorThird: '#fdb927' },
      'Sacramento Kings': { abbreviation: 'SAC', name: 'Sacramento Kings', colorDark: '#5a2d81', colorLight: '#5c6670', colorThird: '#fdb927' },
      'San Antonio Spurs': { abbreviation: 'SAS', name: 'San Antonio Spurs', colorDark: '#c4ced4', colorLight: '#c4ced4', colorThird: '#fdb927' },
      'Toronto Raptors': { abbreviation: 'TOR', name: 'Toronto Raptors', colorDark: '#ce1141', colorLight: '#a0a0a3', colorThird: '#fdb927' },
      'Utah Jazz': { abbreviation: 'UTA', name: 'Utah Jazz', colorDark: '#002b5c', colorLight: '#f9a01b', colorThird: '#fdb927' },
      'Washington Wizards': { abbreviation: 'WAS', name: 'Washington Wizards', colorDark: '#002b5c', colorLight: '#c4ced4', colorThird: '#fdb927' },
      // NHL
      'Anaheim Ducks': { abbreviation: 'ANA', name: 'Anaheim Ducks', colorDark: '#01426A', colorLight: '#F47A38', colorThird: '#F47A38' },
      'Arizona Coyotes': { abbreviation: 'ARI', name: 'Arizona Coyotes', colorDark: '#8C2633', colorLight: '#E2D6B5', colorThird: '#E2D6B5' },
      'Boston Bruins': { abbreviation: 'BOS', name: 'Boston Bruins', colorDark: '#FFB81C', colorLight: '#000000', colorThird: '#000000' },
      'Buffalo Sabres': { abbreviation: 'BUF', name: 'Buffalo Sabres', colorDark: '#002654', colorLight: '#FCB514', colorThird: '#FCB514' },
      'Calgary Flames': { abbreviation: 'CGY', name: 'Calgary Flames', colorDark: '#C8102E', colorLight: '#F1BE48', colorThird: '#F1BE48' },
      'Carolina Hurricanes': { abbreviation: 'CAR', name: 'Carolina Hurricanes', colorDark: '#CC0000', colorLight: '#76232F', colorThird: '#76232F' },
      'Chicago Blackhawks': { abbreviation: 'CHI', name: 'Chicago Blackhawks', colorDark: '#CF0A2C', colorLight: '#FF671B', colorThird: '#FF671B' },
      'Colorado Avalanche': { abbreviation: 'COL', name: 'Colorado Avalanche', colorDark: '#6F263D', colorLight: '#236192', colorThird: '#236192' },
      'Columbus Blue Jackets': { abbreviation: 'CBJ', name: 'Columbus Blue Jackets', colorDark: '#041E42', colorLight: '#A4A9AD', colorThird: '#A4A9AD' },
      'Dallas Stars': { abbreviation: 'DAL', name: 'Dallas Stars', colorDark: '#006847', colorLight: '#8F8F8C', colorThird: '#8F8F8C' },
      'Detroit Red Wings': { abbreviation: 'DET', name: 'Detroit Red Wings', colorDark: '#C8102E', colorLight: '#A2AAAD', colorThird: '#A2AAAD' },
      'Edmonton Oilers': { abbreviation: 'EDM', name: 'Edmonton Oilers', colorDark: '#041E42', colorLight: '#FF4C00', colorThird: '#FF4C00' },
      'Florida Panthers': { abbreviation: 'FLA', name: 'Florida Panthers', colorDark: '#041E42', colorLight: '#C8102E', colorThird: '#C8102E' },
      'Los Angeles Kings': { abbreviation: 'LAK', name: 'Los Angeles Kings', colorDark: '#111111', colorLight: '#A2AAAD', colorThird: '#A2AAAD' },
      'Minnesota Wild': { abbreviation: 'MIN', name: 'Minnesota Wild', colorDark: '#154734', colorLight: '#A6192E', colorThird: '#A6192E' },
      'Montreal Canadiens': { abbreviation: 'MTL', name: 'Montreal Canadiens', colorDark: '#A6192E', colorLight: '#192168', colorThird: '#192168' },
      'Nashville Predators': { abbreviation: 'NSH', name: 'Nashville Predators', colorDark: '#041E42', colorLight: '#FFB81C', colorThird: '#FFB81C' },
      'New Jersey Devils': { abbreviation: 'NJD', name: 'New Jersey Devils', colorDark: '#CE1126', colorLight: '#000000', colorThird: '#000000' },
      'New York Islanders': { abbreviation: 'NYI', name: 'New York Islanders', colorDark: '#00539B', colorLight: '#F47D30', colorThird: '#F47D30' },
      'New York Rangers': { abbreviation: 'NYR', name: 'New York Rangers', colorDark: '#0038A8', colorLight: '#CE1126', colorThird: '#CE1126' },
      'Ottawa Senators': { abbreviation: 'OTT', name: 'Ottawa Senators', colorDark: '#E31837', colorLight: '#C69214', colorThird: '#C69214' },
      'Philadelphia Flyers': { abbreviation: 'PHI', name: 'Philadelphia Flyers', colorDark: '#F74902', colorLight: '#000000', colorThird: '#000000' },
      'Pittsburgh Penguins': { abbreviation: 'PIT', name: 'Pittsburgh Penguins', colorDark: '#FCB514', colorLight: '#000000', colorThird: '#000000' },
      'San Jose Sharks': { abbreviation: 'SJS', name: 'San Jose Sharks', colorDark: '#006D75', colorLight: '#EA7200', colorThird: '#EA7200' },
      'Seattle Kraken': { abbreviation: 'SEA', name: 'Seattle Kraken', colorDark: '#355464', colorLight: '#99D9D9', colorThird: '#99D9D9' },
      'St. Louis Blues': { abbreviation: 'STL', name: 'St. Louis Blues', colorDark: '#002F87', colorLight: '#FCB514', colorThird: '#FCB514' },
      'Tampa Bay Lightning': { abbreviation: 'TBL', name: 'Tampa Bay Lightning', colorDark: '#002868', colorLight: '#041E42', colorThird: '#041E42' },
      'Toronto Maple Leafs': { abbreviation: 'TOR', name: 'Toronto Maple Leafs', colorDark: '#003E7E', colorLight: '#041E42', colorThird: '#041E42' },
      'Vancouver Canucks': { abbreviation: 'VAN', name: 'Vancouver Canucks', colorDark: '#00205B', colorLight: '#00843D', colorThird: '#00843D' },
      'Vegas Golden Knights': { abbreviation: 'VGK', name: 'Vegas Golden Knights', colorDark: '#B4975A', colorLight: '#333F42', colorThird: '#333F42' },
      'Washington Capitals': { abbreviation: 'WSH', name: 'Washington Capitals', colorDark: '#041E42', colorLight: '#C8102E', colorThird: '#C8102E' },
      'Winnipeg Jets': { abbreviation: 'WPG', name: 'Winnipeg Jets', colorDark: '#041E42', colorLight: '#004C97', colorThird: '#004C97' },
        // Countries
      'Afghanistan': { abbreviation: 'AFG', name: '🇦🇫 Afghanistan', colorDark: '#007A3D', colorLight: '#E52B2B', colorThird: '#E52B2B' },
      'Albania': { abbreviation: 'ALB', name: '🇦🇱 Albania', colorDark: '#E41D25', colorLight: '#000000', colorThird: '#ede4e4' },
      'Algeria': { abbreviation: 'ALG', name: '🇩🇿 Algeria', colorDark: '#006233', colorLight: '#D52B1E', colorThird: '#D52B1E' },
      'Argentina': { abbreviation: 'ARG', name: '🇦🇷 Argentina', colorDark: '#75AADB', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },
      'Armenia': { abbreviation: 'ARM', name: '🇦🇲 Armenia', colorDark: '#0033A0', colorLight: '#D90012', colorThird: '#D90012' },
      'Australia': { abbreviation: 'AUS', name: '🇦🇺 Australia', colorDark: '#00843D', colorLight: '#FFCD00', colorThird: '#FFCD00' },
      'Austria': { abbreviation: 'AUT', name: '🇦🇹 Austria', colorDark: '#ED2939', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },
      'Azerbaijan': { abbreviation: 'AZE', name: '🇦🇿 Azerbaijan', colorDark: '#00B3E6', colorLight: '#EF3340', colorThird: '#EF3340' },
      'Bahamas': { abbreviation: 'BAH', name: '🇧🇸 Bahamas', colorDark: '#FFC72C', colorLight: '#00A3E0', colorThird: '#00A3E0' },
      'Bahrain': { abbreviation: 'BHR', name: '🇧🇭 Bahrain', colorDark: '#DA291C', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },
      'Bangladesh': { abbreviation: 'BAN', name: '🇧🇩 Bangladesh', colorDark: '#006A4E', colorLight: '#F42A41', colorThird: '#F42A41' },
      'Barbados': { abbreviation: 'BAR', name: '🇧🇧 Barbados', colorDark: '#00267F', colorLight: '#FFC726', colorThird: '#FFC726' },
      'Belarus': { abbreviation: 'BLR', name: '🇧🇾 Belarus', colorDark: '#00923E', colorLight: '#EF3340', colorThird: '#EF3340' },
      'Belgium': { abbreviation: 'BEL', name: '🇧🇪 Belgium', colorDark: '#000000', colorLight: '#FFD700', colorThird: '#FFD700' },
      'Belize': { abbreviation: 'BIZ', name: '🇧🇿 Belize', colorDark: '#003F87', colorLight: '#EF3340', colorThird: '#EF3340' },
      'Benin': { abbreviation: 'BEN', name: '🇧🇯 Benin', colorDark: '#319B42', colorLight: '#FFD100', colorThird: '#FFD100' },
      'Bhutan': { abbreviation: 'BHU', name: '🇧🇹 Bhutan', colorDark: '#FFCC00', colorLight: '#FF0000', colorThird: '#FF0000' },
      'Bolivia': { abbreviation: 'BOL', name: '🇧🇴 Bolivia', colorDark: '#007934', colorLight: '#FFD700', colorThird: '#FFD700' },
      'Bosnia and Herzegovina': { abbreviation: 'BIH', name: '🇧🇦 Bosnia Herzegovina', colorDark: '#0033A0', colorLight: '#FFD700', colorThird: '#FFD700' },
      'Botswana': { abbreviation: 'BOT', name: '🇧🇼 Botswana', colorDark: '#00BFFF', colorLight: '#000000', colorThird: '#000000' },
      'Brazil': { abbreviation: 'BRA', name: '🇧🇷 Brazil', colorDark: '#009C3B', colorLight: '#FFDF00', colorThird: '#FFDF00' },
      'Brunei': { abbreviation: 'BRU', name: '🇧🇳 Brunei', colorDark: '#FFD100', colorLight: '#000000', colorThird: '#000000' },
      'Bulgaria': { abbreviation: 'BUL', name: '🇧🇬 Bulgaria', colorDark: '#00966E', colorLight: '#D62612', colorThird: '#D62612' },
      'Burkina Faso': { abbreviation: 'BUR', name: '🇧🇫 Burkina Faso', colorDark: '#EF3340', colorLight: '#009739', colorThird: '#009739' },
      'Burundi': { abbreviation: 'BDI', name: '🇧🇮 Burundi', colorDark: '#007849', colorLight: '#EF3340', colorThird: '#EF3340' },
      'Cambodia': { abbreviation: 'CAM', name: '🇰🇭 Cambodia', colorDark: '#032EA1', colorLight: '#EE1C25', colorThird: '#EE1C25' },
      'Cameroon': { abbreviation: 'CMR', name: '🇨🇲 Cameroon', colorDark: '#007A5E', colorLight: '#FECC00', colorThird: '#FECC00' },
      'Canada': { abbreviation: 'CAN', name: '🇨🇦 Canada', colorDark: '#FF0000', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },

      'Chile': { abbreviation: 'CHI', name: '🇨🇱 Chile', colorDark: '#D52B1E', colorLight: '#0033A0', colorThird: '#0033A0' },
    'China': { abbreviation: 'CHN', name: '🇨🇳 China', colorDark: '#FFDE00', colorLight: '#DE2910', colorThird: '#DE2910' },
    'Colombia': { abbreviation: 'COL', name: '🇨🇴 Colombia', colorDark: '#FFD700', colorLight: '#0033A0', colorThird: '#0033A0' },
    'Costa Rica': { abbreviation: 'CRC', name: '🇨🇷 Costa Rica', colorDark: '#002B7F', colorLight: '#CE1126', colorThird: '#CE1126' },
    'Croatia': { abbreviation: 'CRO', name: '🇭🇷 Croatia', colorDark: '#171796', colorLight: '#FF0000', colorThird: '#FF0000' },
    'Cuba': { abbreviation: 'CUB', name: '🇨🇺 Cuba', colorDark: '#002A8F', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },
    'Cyprus': { abbreviation: 'CYP', name: '🇨🇾 Cyprus', colorDark: '#000000', colorLight: '#FF7900', colorThird: '#FF7900' },
    'Czech Republic': { abbreviation: 'CZE', name: '🇨🇿 Czech Republic', colorDark: '#11457E', colorLight: '#D7141A', colorThird: '#D7141A' },
    'Denmark': { abbreviation: 'DEN', name: '🇩🇰 Denmark', colorDark: '#C60C30', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },
    'Dominican Republic': { abbreviation: 'DOM', name: '🇩🇴 Dominican Republic', colorDark: '#002D62', colorLight: '#CE1126', colorThird: '#CE1126' },
    'Ecuador': { abbreviation: 'ECU', name: '🇪🇨 Ecuador', colorDark: '#0033A0', colorLight: '#FFD100', colorThird: '#FFD100' },
    'Egypt': { abbreviation: 'EGY', name: '🇪🇬 Egypt', colorDark: '#006233', colorLight: '#CE1126', colorThird: '#CE1126' },
    'El Salvador': { abbreviation: 'SLV', name: '🇸🇻 El Salvador', colorDark: '#0C4DA2', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },
    'England': { abbreviation: 'ENG', name: '🏴 England', colorDark: '#CF142B', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },
    'Estonia': { abbreviation: 'EST', name: '🇪🇪 Estonia', colorDark: '#0072CE', colorLight: '#000000', colorThird: '#000000' },
    'Ethiopia': { abbreviation: 'ETH', name: '🇪🇹 Ethiopia', colorDark: '#EC2127', colorLight: '#008B3E', colorThird: '#008B3E' },
    'Fiji': { abbreviation: 'FIJ', name: '🇫🇯 Fiji', colorDark: '#5FB4DD', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },
    'Finland': { abbreviation: 'FIN', name: '🇫🇮 Finland', colorDark: '#003580', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },
    'France': { abbreviation: 'FRA', name: '🇫🇷 France', colorDark: '#0055A4', colorLight: '#EF4135', colorThird: '#EF4135' },
    'Gabon': { abbreviation: 'GAB', name: '🇬🇦 Gabon', colorDark: '#3A75C4', colorLight: '#FFD700', colorThird: '#FFD700' },
    'Gambia': { abbreviation: 'GAM', name: '🇬🇲 Gambia', colorDark: '#3A75C4', colorLight: '#CE1126', colorThird: '#CE1126' },
    'Georgia': { abbreviation: 'GEO', name: '🇬🇪 Georgia', colorDark: '#C60C30', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },
    'Germany': { abbreviation: 'GER', name: '🇩🇪 Germany', colorDark: '#DD0000', colorLight: '#FFCC00', colorThird: '#FFCC00' },
    'Ghana': { abbreviation: 'GHA', name: '🇬🇭 Ghana', colorDark: '#006B3F', colorLight: '#FCD116', colorThird: '#FCD116' },
    'Greece': { abbreviation: 'GRE', name: '🇬🇷 Greece', colorDark: '#0D5EAF', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },
    'Grenada': { abbreviation: 'GRN', name: '🇬🇩 Grenada', colorDark: '#007849', colorLight: '#EF3340', colorThird: '#EF3340' },
    'Guatemala': { abbreviation: 'GUA', name: '🇬🇹 Guatemala', colorDark: '#4997D0', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },
    'Guinea': { abbreviation: 'GUI', name: '🇬🇳 Guinea', colorDark: '#CE1126', colorLight: '#FCD116', colorThird: '#FCD116' },
    'Guyana': { abbreviation: 'GUY', name: '🇬🇾 Guyana', colorDark: '#009739', colorLight: '#FFD100', colorThird: '#FFD100' },
    'Haiti': { abbreviation: 'HAI', name: '🇭🇹 Haiti', colorDark: '#00209F', colorLight: '#E30A17', colorThird: '#E30A17' },
    'Honduras': { abbreviation: 'HON', name: '🇭🇳 Honduras', colorDark: '#0038A8', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },
    'Hungary': { abbreviation: 'HUN', name: '🇭🇺 Hungary', colorDark: '#477050', colorLight: '#CE2939', colorThird: '#CE2939' },
    'Iceland': { abbreviation: 'ICE', name: '🇮🇸 Iceland', colorDark: '#003897', colorLight: '#D72828', colorThird: '#D72828' },
    'India': { abbreviation: 'IND', name: '🇮🇳 India', colorDark: '#046A38', colorLight: '#FF671F', colorThird: '#FF671F' },
    'Indonesia': { abbreviation: 'INA', name: '🇮🇩 Indonesia', colorDark: '#CE1126', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },
    'Iran': { abbreviation: 'IRN', name: '🇮🇷 Iran', colorDark: '#DA0000', colorLight: '#239F40', colorThird: '#239F40' },
    'Iraq': { abbreviation: 'IRQ', name: '🇮🇶 Iraq', colorDark: '#CE1126', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },
    'Ireland': { abbreviation: 'IRL', name: '🇮🇪 Ireland', colorDark: '#169B62', colorLight: '#FF883E', colorThird: '#FF883E' },
    'Israel': { abbreviation: 'ISR', name: '🇮🇱 Israel', colorDark: '#0038B8', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },
    'Italy': { abbreviation: 'ITA', name: '🇮🇹 Italy', colorDark: '#008C45', colorLight: '#CD212A', colorThird: '#CD212A' },
    'Jamaica': { abbreviation: 'JAM', name: '🇯🇲 Jamaica', colorDark: '#FFD100', colorLight: '#007847', colorThird: '#007847' },
    'Japan': { abbreviation: 'JPN', name: '🇯🇵 Japan', colorDark: '#BC002D', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },
    'Jordan': { abbreviation: 'JOR', name: '🇯🇴 Jordan', colorDark: '#007A33', colorLight: '#000000', colorThird: '#000000' },
    'Kazakhstan': { abbreviation: 'KAZ', name: '🇰🇿 Kazakhstan', colorDark: '#00AEEF', colorLight: '#FFD700', colorThird: '#FFD700' },
    'Kenya': { abbreviation: 'KEN', name: '🇰🇪 Kenya', colorDark: '#BD0D18', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },  
    'Kuwait': { abbreviation: 'KUW', name: '🇰🇼 Kuwait', colorDark: '#007A33', colorLight: '#CE1126', colorThird: '#CE1126' },  
    'Kyrgyzstan': { abbreviation: 'KGZ', name: '🇰🇬 Kyrgyzstan', colorDark: '#EA0029', colorLight: '#FFD700', colorThird: '#FFD700' },  
    'Laos': { abbreviation: 'LAO', name: '🇱🇦 Laos', colorDark: '#CC0033', colorLight: '#0033A0', colorThird: '#0033A0' },  
    'Latvia': { abbreviation: 'LVA', name: '🇱🇻 Latvia', colorDark: '#9E3039', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },  
    'Lebanon': { abbreviation: 'LBN', name: '🇱🇧 Lebanon', colorDark: '#ED1B2F', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },  
    'Lesotho': { abbreviation: 'LES', name: '🇱🇸 Lesotho', colorDark: '#00209F', colorLight: '#009739', colorThird: '#009739' },  
    'Liberia': { abbreviation: 'LBR', name: '🇱🇷 Liberia', colorDark: '#BD3D44', colorLight: '#0F4EA3', colorThird: '#0F4EA3' },  
    'Libya': { abbreviation: 'LBA', name: '🇱🇾 Libya', colorDark: '#239E46', colorLight: '#D52B1E', colorThird: '#D52B1E' },  
    'Lithuania': { abbreviation: 'LTU', name: '🇱🇹 Lithuania', colorDark: '#FDB913', colorLight: '#007A33', colorThird: '#007A33' },  
    'Luxembourg': { abbreviation: 'LUX', name: '🇱🇺 Luxembourg', colorDark: '#00A1DE', colorLight: '#EF3340', colorThird: '#EF3340' },  
    'Madagascar': { abbreviation: 'MAD', name: '🇲🇬 Madagascar', colorDark: '#007E3A', colorLight: '#FC3D21', colorThird: '#FC3D21' },  
    'Malawi': { abbreviation: 'MAW', name: '🇲🇼 Malawi', colorDark: '#CE1126', colorLight: '#000000', colorThird: '#000000' },  
    'Malaysia': { abbreviation: 'MAS', name: '🇲🇾 Malaysia', colorDark: '#010066', colorLight: '#CC092F', colorThird: '#CC092F' },  
    'Maldives': { abbreviation: 'MDV', name: '🇲🇻 Maldives', colorDark: '#D21034', colorLight: '#007E3A', colorThird: '#007E3A' },  
    'Mali': { abbreviation: 'MLI', name: '🇲🇱 Mali', colorDark: '#14B53A', colorLight: '#FCD116', colorThird: '#FCD116' },  
    'Malta': { abbreviation: 'MLT', name: '🇲🇹 Malta', colorDark: '#C8102E', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },  
    'Mauritania': { abbreviation: 'MTN', name: '🇲🇷 Mauritania', colorDark: '#006233', colorLight: '#FFD100', colorThird: '#FFD100' },  
    'Mauritius': { abbreviation: 'MRI', name: '🇲🇺 Mauritius', colorDark: '#1A206D', colorLight: '#EC1920', colorThird: '#EC1920' },  
    'Mexico': { abbreviation: 'MEX', name: '🇲🇽 Mexico', colorDark: '#006341', colorLight: '#CE1126', colorThird: '#CE1126' },  
    'Moldova': { abbreviation: 'MDA', name: '🇲🇩 Moldova', colorDark: '#0033A0', colorLight: '#FFD700', colorThird: '#FFD700' },  
    'Mongolia': { abbreviation: 'MGL', name: '🇲🇳 Mongolia', colorDark: '#C4272F', colorLight: '#0033A0', colorThird: '#0033A0' },  
    'Montenegro': { abbreviation: 'MNE', name: '🇲🇪 Montenegro', colorDark: '#CE1126', colorLight: '#D3A408', colorThird: '#D3A408' },  
    'Morocco': { abbreviation: 'MAR', name: '🇲🇦 Morocco', colorDark: '#C1272D', colorLight: '#006233', colorThird: '#006233' },  
    'Mozambique': { abbreviation: 'MOZ', name: '🇲🇿 Mozambique', colorDark: '#FDBB30', colorLight: '#CE1126', colorThird: '#CE1126' },  
    'Myanmar': { abbreviation: 'MYA', name: '🇲🇲 Myanmar', colorDark: '#FFD600', colorLight: '#34B233', colorThird: '#34B233' },  
    'Namibia': { abbreviation: 'NAM', name: '🇳🇦 Namibia', colorDark: '#0033A0', colorLight: '#FFD100', colorThird: '#FFD100' },  
    'Nepal': { abbreviation: 'NEP', name: '🇳🇵 Nepal', colorDark: '#00205B', colorLight: '#DC143C', colorThird: '#DC143C' },  
    'Netherlands': { abbreviation: 'NED', name: '🇳🇱 Netherlands', colorDark: '#21468B', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },  
    'New Zealand': { abbreviation: 'NZL', name: '🇳🇿 New Zealand', colorDark: '#00247D', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },  
    'Nicaragua': { abbreviation: 'NCA', name: '🇳🇮 Nicaragua', colorDark: '#0033A0', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },  
    'Niger': { abbreviation: 'NIG', name: '🇳🇪 Niger', colorDark: '#0DB02B', colorLight: '#E05206', colorThird: '#E05206' },  
    'Nigeria': { abbreviation: 'NGR', name: '🇳🇬 Nigeria', colorDark: '#008751', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },  
    'North Macedonia': { abbreviation: 'MKD', name: '🇲🇰 North Macedonia', colorDark: '#CE1126', colorLight: '#FFD700', colorThird: '#FFD700' },  
    'Norway': { abbreviation: 'NOR', name: '🇳🇴 Norway', colorDark: '#BA0C2F', colorLight: '#00205B', colorThird: '#00205B' },  
    'Oman': { abbreviation: 'OMA', name: '🇴🇲 Oman', colorDark: '#007A33', colorLight: '#C8102E', colorThird: '#C8102E' },  
    'Pakistan': { abbreviation: 'PAK', name: '🇵🇰 Pakistan', colorDark: '#01411C', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },  
    'Palestine': { abbreviation: 'PLE', name: '🇵🇸 Palestine', colorDark: '#009739', colorLight: '#000000', colorThird: '#000000' },  
    'Panama': { abbreviation: 'PAN', name: '🇵🇦 Panama', colorDark: '#005AA7', colorLight: '#D21034', colorThird: '#D21034' },  
    'Papua New Guinea': { abbreviation: 'PNG', name: '🇵🇬 Papua New Guinea', colorDark: '#000000', colorLight: '#C8102E', colorThird: '#C8102E' },  
    'Paraguay': { abbreviation: 'PAR', name: '🇵🇾 Paraguay', colorDark: '#0038A8', colorLight: '#D52B1E', colorThird: '#D52B1E' },  
    'Peru': { abbreviation: 'PER', name: '🇵🇪 Peru', colorDark: '#D91023', colorLight: '#D91023', colorThird: '#D91023' },  
    'Philippines': { abbreviation: 'PHI', name: '🇵🇭 Philippines', colorDark: '#0038A8', colorLight: '#CE1126', colorThird: '#CE1126' },  
    'Poland': { abbreviation: 'POL', name: '🇵🇱 Poland', colorDark: '#C8102E', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },  
    'Portugal': { abbreviation: 'POR', name: '🇵🇹 Portugal', colorDark: '#D21034', colorLight: '#00A652', colorThird: '#00A652' },  
    'Qatar': { abbreviation: 'QAT', name: '🇶🇦 Qatar', colorDark: '#A80B28', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },  
    'Romania': { abbreviation: 'ROU', name: '🇷🇴 Romania', colorDark: '#CE1126', colorLight: '#004B87', colorThird: '#004B87' },  
    'Russia': { abbreviation: 'RUS', name: '🇷🇺 Russia', colorDark: '#D52B1E', colorLight: '#0033A0', colorThird: '#0033A0' },  
    'Rwanda': { abbreviation: 'RWA', name: '🇷🇼 Rwanda', colorDark: '#007B38', colorLight: '#FFD100', colorThird: '#FFD100' },  
    'Saudi Arabia': { abbreviation: 'KSA', name: '🇸🇦 Saudi Arabia', colorDark: '#005EA6', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },  
    'Senegal': { abbreviation: 'SEN', name: '🇸🇳 Senegal', colorDark: '#008D4D', colorLight: '#FFD600', colorThird: '#FFD600' },  
    'Serbia': { abbreviation: 'SRB', name: '🇷🇸 Serbia', colorDark: '#C8102E', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },  
    'Seychelles': { abbreviation: 'SEY', name: '🇸🇨 Seychelles', colorDark: '#E5E0E4', colorLight: '#000000', colorThird: '#000000' },  
    'Sierra Leone': { abbreviation: 'SLE', name: '🇸🇱 Sierra Leone', colorDark: '#F4D03F', colorLight: '#006C32', colorThird: '#006C32' },  
    'Singapore': { abbreviation: 'SGP', name: '🇸🇬 Singapore', colorDark: '#FF0000', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },  
    'Slovakia': { abbreviation: 'SVK', name: '🇸🇰 Slovakia', colorDark: '#002A5C', colorLight: '#FF0000', colorThird: '#FF0000' },  
    'Slovenia': { abbreviation: 'SLO', name: '🇸🇮 Slovenia', colorDark: '#005A9C', colorLight: '#FF0000', colorThird: '#FF0000' },  
    'Solomon Islands': { abbreviation: 'SOL', name: '🇸🇧 Solomon Islands', colorDark: '#007A33', colorLight: '#FFD600', colorThird: '#FFD600' },  
    'South Africa': { abbreviation: 'RSA', name: '🇿🇦 South Africa', colorDark: '#007A33', colorLight: '#FF0000', colorThird: '#FF0000' },  
    'South Korea': { abbreviation: 'KOR', name: '🇰🇷 South Korea', colorDark: '#C8102E', colorLight: '#003DA5', colorThird: '#003DA5' },  
    'Spain': { abbreviation: 'ESP', name: '🇪🇸 Spain', colorDark: '#AA141E', colorLight: '#F1BF00', colorThird: '#F1BF00' },  
    'Sri Lanka': { abbreviation: 'SRI', name: '🇱🇰 Sri Lanka', colorDark: '#009A43', colorLight: '#FF7F27', colorThird: '#FF7F27' },  
    'Sudan': { abbreviation: 'SUD', name: '🇸🇩 Sudan', colorDark: '#C8102E', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },  
    'Sweden': { abbreviation: 'SWE', name: '🇸🇪 Sweden', colorDark: '#005CBF', colorLight: '#FFC720', colorThird: '#FFC720' },  
    'Switzerland': { abbreviation: 'SUI', name: '🇨🇭 Switzerland', colorDark: '#C8102E', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },  
    'Syria': { abbreviation: 'SYR', name: '🇸🇾 Syria', colorDark: '#C8102E', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },  
    'Taiwan': { abbreviation: 'TPE', name: '🇹🇼 Taiwan', colorDark: '#008C45', colorLight: '#FF0000', colorThird: '#FF0000' },  
    'Tajikistan': { abbreviation: 'TJK', name: '🇹🇯 Tajikistan', colorDark: '#E3CBA0', colorLight: '#DA291C', colorThird: '#DA291C' },  
    'Tanzania': { abbreviation: 'TZA', name: '🇹🇿 Tanzania', colorDark: '#007A33', colorLight: '#FFD600', colorThird: '#FFD600' },  
    'Thailand': { abbreviation: 'THA', name: '🇹🇭 Thailand', colorDark: '#D71000', colorLight: '#0000A0', colorThird: '#0000A0' },  
    'Togo': { abbreviation: 'TOG', name: '🇹🇬 Togo', colorDark: '#007A33', colorLight: '#FFD600', colorThird: '#FFD600' },  
    'Tonga': { abbreviation: 'TON', name: '🇹🇴 Tonga', colorDark: '#C8102E', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },  
    'Trinidad and Tobago': { abbreviation: 'TTO', name: '🇹🇹 Trinidad and Tobago', colorDark: '#C8102E', colorLight: '#000000', colorThird: '#000000' },  
    'Tunisia': { abbreviation: 'TUN', name: '🇹🇳 Tunisia', colorDark: '#E63E32', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },  
    'Turkey': { abbreviation: 'TUR', name: '🇹🇷 Turkey', colorDark: '#E30E2B', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },  
    'Uganda': { abbreviation: 'UGA', name: '🇺🇬 Uganda', colorDark: '#FFD600', colorLight: '#FF0000', colorThird: '#FF0000' },  
    'Ukraine': { abbreviation: 'UKR', name: '🇺🇦 Ukraine', colorDark: '#005EB8', colorLight: '#FFD500', colorThird: '#FFD500' },  
    'United Arab Emirates': { abbreviation: 'UAE', name: '🇦🇪 United Arab Emirates', colorDark: '#008C45', colorLight: '#FF0000', colorThird: '#FF0000' },  
    'United Kingdom': { abbreviation: 'GBR', name: '🇬🇧 United Kingdom', colorDark: '#003DA5', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },  
    'United States': { abbreviation: 'USA', name: '🇺🇸 United States', colorDark: '#B22234', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },  
    'Uruguay': { abbreviation: 'URU', name: '🇺🇾 Uruguay', colorDark: '#5E9F4B', colorLight: '#FDD835', colorThird: '#FDD835' },  
    'Uzbekistan': { abbreviation: 'UZB', name: '🇺🇿 Uzbekistan', colorDark: '#1E8BC3', colorLight: '#FFFFFF', colorThird: '#FFFFFF' },  
    'Vanuatu': { abbreviation: 'VAN', name: '🇻🇺 Vanuatu', colorDark: '#CE1126', colorLight: '#FFCC00', colorThird: '#FFCC00' },  
    'Vatican City': { abbreviation: 'VAT', name: '🇻🇦 Vatican City', colorDark: '#F5D234', colorLight: '#D32A31', colorThird: '#D32A31' },  
    'Venezuela': { abbreviation: 'VEN', name: '🇻🇪 Venezuela', colorDark: '#A40E24', colorLight: '#FFD300', colorThird: '#FFD300' },  
    'Vietnam': { abbreviation: 'VIE', name: '🇻🇳 Vietnam', colorDark: '#DA251D', colorLight: '#FFDA44', colorThird: '#FFDA44' },  
    'Zambia': { abbreviation: 'ZAM', name: '🇿🇲 Zambia', colorDark: '#F1BF00', colorLight: '#C8102E', colorThird: '#C8102E' },  
    'Zimbabwe': { abbreviation: 'ZIM', name: '🇿🇼 Zimbabwe', colorDark: '#5A9107', colorLight: '#FFC700', colorThird: '#FFC700' },

   // Default color and abbreviation for unknown teams
   default: { colorDark: '#000000', colorLight: '#FFFFFF', colorThird: '#666666', abbreviation: 'N/A', name: teamName },
  }[teamName] || {
    colorDark: '#000000',
    colorLight: '#FFFFFF',
    colorThird: '#666666',
    abbreviation: 'N/A',
    name: teamName,
  };

  // Wrap color properties in Tailwind classes
  const wrapInTailwind = (color: string) => (text ? `text-[${color}]` : `bg-[${color}]`);

  return {
    ...teamData,
    colorDark: wrapInTailwind(teamData.colorDark),
    colorLight: wrapInTailwind(teamData.colorLight),
    colorThird: wrapInTailwind(teamData.colorThird),
  };
};